[project]
name = "atomic-scattering-factors"
version = "0.2.0"
description = "Calculate X-ray atomic scattering factors and effective electron densities."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "scipy",
    "periodictable",
    "xraylabtool",
]
[project.optional-dependencies]
test = [
    "pytest",
]